Feature/css styles-mainvisual-aboutを作成しました
mitkhs/Website-lesson pull request #12
Opened 2023-05-19 07:16 UTC by mitkhs

## 概要
- メインビジュアルとAboutのレイアウトを修正しました。
- メイン画像を追加しました。
## 確認項目
- 正しく記述できているか確認お願いします。
- メイン画像の右寄せができていません。コンテンツ間の調整は右寄せの実装の時に再度調整します。

[デザイン](https://www.figma.com/file/DocCf831ifn1wq7LrrVHyF/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=249%3A996&t=13PQ1y3Mue4634Ps-1)

2023-05-23 06:27 UTC, mitkhs commented
## 概要
- index.htmlのレイアウトを修正しました。
- メンバー画像を追加しました。
## 確認項目
- 正しく記述できているか確認お願いします。
- ブラウザで確認し、Figmaのデザイン案のレイアウトを少し変更したものになっています。
- SNSのアイコンはテキストに置き換えていますが、アイコン画像を作成しようかと考えています。

[Figmaデザイン](https://www.figma.com/file/DocCf831ifn1wq7LrrVHyF/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=249%3A996&t=13PQ1y3Mue4634Ps-1)

2023-05-23 06:38 UTC, oathkite requested changes

2023-05-23 06:38 UTC, oathkite commented on css/style.css
>  h1 {
タグにそのままスタイルを指定するのはバッドプラクティスなのでやめましょう。
同じ見た目でタグを変えたい場合にスタイルが崩れてしまうためです。

必ず何かしらのクラスをつけてスタイルを指定してください。

2023-05-23 10:19 UTC, mitkhs commented
## 概要
- スタイルを指定するタグ全てにクラスをつけました。
## 確認項目
- 正しく記述できているか確認お願いします。

[デザイン](https://www.figma.com/file/DocCf831ifn1wq7LrrVHyF/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=249%3A996&t=13PQ1y3Mue4634Ps-1)

2023-05-24 03:35 UTC, mitkhs commented
## 概要
- Header内のlinkのスタイルが崩れていたので修正しました。
- paddingやgapの調整をしました。
## 確認項目
- 正しく記述できているか確認お願いします。
[デザイン](https://www.figma.com/file/DocCf831ifn1wq7LrrVHyF/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?type=design&node-id=249%3A996&t=13PQ1y3Mue4634Ps-1)

2023-05-24 03:47 UTC, oathkite requested changes

2023-05-24 03:47 UTC, oathkite commented on css/style.css
> +  .logo {
クラスの前に不要なスペースが入ってるので削除してください。
綺麗に書くのはすごく大切！

2023-05-24 03:47 UTC, oathkite commented on css/style.css
> +  .header-link {
不要なスペースあり。全体的に見直してみて〜

2023-05-24 03:57 UTC, mitkhs commented
## 概要
不要なスペースを削除しました。
確認お願いします！

2023-05-24 04:00 UTC, oathkite approved these changes

2023-05-24 04:00 UTC, oathkite commented on index.html
> +                <a class="header-link" href="#">Contact</a>
いいね！ 👍🏻

2023-05-24 04:04 UTC, mitkhs commented on index.html
> +                <a class="header-link" href="#">Contact</a>
ありがとうございます！
このブランチをマージしてmedia queryの作業ブランチにpullしようと思います。

2023-05-24 06:19 UTC, merged